name: compatibility

on:
  push:
  workflow_call:

jobs:
  convert-adguard:
    uses: NexusSfan/hosts/.github/workflows/convert_adguard.yml@dev
  convert-dnsmasq:
    uses: NexusSfan/hosts/.github/workflows/convert_dnsmasq.yml@dev
  deploy:
    uses: NexusSfan/hosts/.github/workflows/static.yml@dev
